version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Installing composer deps
      - composer install --no-ansi --no-interaction --no-progress --no-scripts --optimize-autoloader

  post_build:
    commands:
      - echo Build completed on `date`
      - ./vendor/bin/phpunit